### ISSUE TITLE
kunai docker stats returns nothing

### ISSUE THREAD

**Issue by Issif** [naparuba/kunai#9]
````
[root:/etc/default] 11s 2 # kunai docker stats
========== [Docker Stats]:
````
Nothing in logs (I started a kunai agent in foreground).

For my docker (i use docker unix socket) : 
````
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa
````
On linuxmint 17 Qiana.

For docker-py
````
Name: docker-py
Version: 0.7.1
Location: /usr/local/lib/python2.7/dist-packages
````

As naparuba adviced me I tried this script : 
````python
from docker import Client
con = Client(base_url='unix://var/run/docker.sock')
print con.containers()
````
I got this error : 
````
Traceback (most recent call last):
  File "./tt.py", line 3, in <module>
    print con.containers()
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 519, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 98, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 94, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.16, server: 1.15)")
````

**Comment by naparuba** [comment]
I just fixed it, we don't need anymore the docker-py lib.

Can you confirm? thanks :)

**Comment by Issif** [comment]
Ok, I pull / update and tell you what.

**Comment by naparuba** [comment]
^^

**Comment by Issif** [comment]
It's OK.

A ``kunai --update```or a ``kunai --upgrare`` didn't work, so I removed */usr/local/lib/python2.7/dist-packages/Kunai-0.8-py2.7.egg* and reinstalled everything.

After that, a ```kunai docker stats`` gave me that : 

````
$ kunai docker stats
========== [Docker Stats]:
========== [Container:c7b4659ea95112060a25176716b7b4d0a7825d127f19a2ccce56e097d0be0212]:
cpu.system:                   0.278263883724
cpu.user:                     0.885295060674
memory.active_anon:           266960896
memory.active_file:           23678976
memory.cache:                 66945024
memory.inactive_anon:         20480
memory.inactive_file:         43094016
memory.mapped_file:           16318464
memory.pgfault:               2055.6868193
memory.pgmajfault:            2.27760474223
memory.pgpgin:                2341.37767501
memory.pgpgout:               1843.77055198
memory.rss:                   266809344
memory.unevictable:           0
========== [Image:kaas:latest (sum)]:
cpu.system:                   0.278263883724
cpu.user:                     0.885295060674
memory.active_anon:           266960896
memory.active_file:           23678976
memory.cache:                 66945024
memory.inactive_anon:         20480
memory.inactive_file:         43094016
memory.mapped_file:           16318464
memory.pgfault:               2055.6868193
memory.pgmajfault:            2.27760474223
memory.pgpgin:                2341.37767501
memory.pgpgout:               1843.77055198
memory.rss:                   266809344
memory.unevictable:           0
````
 Thanks

**Comment by naparuba** [comment]
There is no such kunai --upgrade. It's up to your packet manager to manage this ^^

**Comment by naparuba** [comment]
it's just python setup.py install and that's all :)
